# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13test_protocol.proto\"=\n\x0b\x45ntitySmall\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x11\n\ttimestamp\x18\x02 \x01(\x0c\x12\x0f\n\x07padding\x18\x03 \x01(\x0c\"=\n\x0b\x45ntityLarge\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x11\n\ttimestamp\x18\x02 \x01(\x0c\x12\x0f\n\x07padding\x18\x03 \x01(\x0c\"0\n\x0e\x45ntitySetSmall\x12\x1e\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0c.EntitySmall\"0\n\x0e\x45ntitySetLarge\x12\x1e\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0c.EntityLargeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENTITYSMALL']._serialized_start=23
  _globals['_ENTITYSMALL']._serialized_end=84
  _globals['_ENTITYLARGE']._serialized_start=86
  _globals['_ENTITYLARGE']._serialized_end=147
  _globals['_ENTITYSETSMALL']._serialized_start=149
  _globals['_ENTITYSETSMALL']._serialized_end=197
  _globals['_ENTITYSETLARGE']._serialized_start=199
  _globals['_ENTITYSETLARGE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
